# Default parameters, which can be superseded by CL arguments or
# config files
_param_defaults_shared = {
    "immode": "vid",
    "verbose": 1,
    "gpu_id": "0",
    "loss": "mask_nan_keep_loss",
    "start_batch": 0,
    "exp": None,
    "viddir": None,
    "io_config": None,
    "crop_height": None,
    "crop_width": None,
    "n_channels_in": None,
    "new_n_channels_out": None,
    "camnames": None,
    "downfac": None,
    "extension": None,
    "n_views": 6,
    "batch_size": None,
    "max_queue_size": None,
    "workers": None,
    "epochs": None,
    "train_mode": None,
    "vid_dir_flag": None,
    "num_validation_per_exp": None,
    "chunks": None,
    "lockfirst": None,
    "cam3_train": None,
    "debug_volume_tifdir": None, 
    "vol_size": None,
    "load_valid": None,
}
_param_defaults_dannce = {
    "metric": ["euclidean_distance_3D"],
    "sigma": 10,
    "lr": 1e-3,
    "n_layers_locked": 2,
    "interp": "nearest",
    "depth": False,
    "rotate": True,
    "predict_mode": "torch",
    "comthresh": 0,
    "weighted": False,
    "com_method": "median",
    "channel_combo": None,
    "new_last_kernel_size": [3, 3, 3],
    "n_channels_out": 20,
    "cthresh": 350,
    "medfilt_window": None,
    "com_fromlabels": False,
    "augment_hue": False,
    "augment_brightness": False,
    "augment_continuous_rotation": False,
    "dannce_train_dir": None,
    "dannce_predict_dir": None,
    "dannce_predict_model": None,
    "dannce_finetune_weights": None,
    "com_file": None,
    "vmin": None,
    "vmax": None,
    "nvox": None,
    "retriangulate": None,
    "distort": None,
    "batch_norm": None,
    "instance_norm": None,
    "expval": None,
    "com_thresh": None,
    "max_num_samples": None,
    "all_cams": None,
    "start_sample": None,
}
_param_defaults_com = {
    "dsmode": "nn",
    "sigma": 30,
    "debug": False,
    "lr": 5e-5,
    "net": "unet2d_fullbn",
    "n_channels_out": 1,
    "com_train_dir": None,
    "com_predict_dir": None,
    "com_finetune_weights": None,
    "com_predict_weights": None,
    "com_debug": None,
    "com_exp": None,
}
